// This file is automatically generated. Do not edit it directly.
//import { createClient } from '@supabase/supabase-js';
//import type { Database } from './types';

//const SUPABASE_URL = "https://plqbgrotkqedpeabhbdb.supabase.co";
//const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBscWJncm90a3FlZHBlYWJoYmRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0Njg4MTEsImV4cCI6MjA3MDA0NDgxMX0.3vozT1w3yfDUNtqyLEKhk24dA67w2_Y0mPGXtnl_Axk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

//export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
//  auth: {
//    storage: localStorage,
//    persistSession: true,
//    autoRefreshToken: true,
//  }
//});


import { createClient } from "@supabase/supabase-js";
import type { Database } from "@/types/supabase";

const SUPABASE_URL = "https://plqbgrotkqedpeabhbdb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBscWJncm90a3FlZHBlYWJoYmRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0Njg4MTEsImV4cCI6MjA3MDA0NDgxMX0.3vozT1w3yfDUNtqyLEKhk24dA67w2_Y0mPGXtnl_Axk";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);

